version: '3'
services:
  postgres:
    image: postgres
    environment:
      - 'POSTGRES_PASSWORD=12345'
    ports:
      - "5433:5432"
  main:
    build: .
    depends_on:
      - postgres
    networks:
      - default
    ports:
      - "8090:8090"